{ "name": "Hospital Management System ",
    "version": "1.0",
    "summary": "A complete Hospital Management System to manage patients, doctors, staff, appointments, and hospital operations efficiently",
    "sequence": 10,
    "description": """
        The Healing HMS - Patient Management Module
        - Manage patients, medical history, and appointments
        - Role-based access for staff and admin
        - Integration with other hospital modules
    """,
    "category": "Healthcare",
    "author": "The Healing Coders (Aliaa, Mariam, Lama)",
'depends': ['base', 'contacts', 'product', 'mail', 'account'],

    'data': [
        'security/groups.xml', 
        'security/ir.model.access.csv', 
        'views/hospital_custom_menu.xml',
        'views/custom_dashboard_menu.xml',
         'views/hospital_menu.xml', 
        'views/hospital_dashboard_menu.xml',
        'views/room.xml',          
        'views/hospital_department_views.xml',
        'views/hospital_room_booking_views.xml', 
        'views/staff_views.xml',
        'views/hospital_billing_views.xml',
        'data/specialization_sequence.xml',
        'data/staff_sequence.xml',
        'data/billing_sequence.xml',
        'data/pharmacy_sequences.xml',
        'views/hospital_pharmacy_views.xml',
        'reports/hospital_billing_report.xml',
        'views/appointment_views.xml',
        'views/prescription.xml',
        'views/patient.xml',
        'reports/report_patient_history_view.xml',
        'views/insurance_views.xml',
        'views/blood_bag_views.xml',
        'views/donor_views.xml',
        'views/transfusion_views.xml',
        'views/ambulance_views.xml',
        'data/lab_request_sequence.xml',
        'views/lab_test_type_views.xml',
        'reports/report_lab_request_with_results.xml',
        'views/lab_request_views.xml',
        'reports/report_lab_result.xml',
        'views/lab_result_views.xml',
        'views/ambulance_request_views.xml',
        'views/hospital_dashboard_views.xml',
        'views/room.dashboard.xml',
        'views/department_dashboard.xml',
        'views/pharmacy_dashboard.xml',
        'views/blood_bank_dashboard.xml',
        'reports/report_prescription.xml',
        'views/patient_history_views.xml',
        'data/patient_history_sequence.xml',
        'data/prescription_sequence.xml',
        'data/sequence_patient.xml',],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}