# custom_addons/hospital_departments/models/__init__.py
from . import doctor
from . import department
from . import patient
from . import hospital_room
from . import Specialization
from . import hospital_room_booking
from . import medical_record
from . import staff
from . import billing
from . import appointment
from . import hospital_pharmacy
from . import hospital_insurance
from . import ambulance
from . import ambulance_request
from . import driver
from . import donor
from . import blood_bag
from . import transfusion