# custom_addons/hospital_departments/models/__init__.py
from . import department
from . import patient
from . import hospital_room
from . import Specialization
from . import hospital_room_booking
from . import staff
from . import billing
from . import appointment
from . import hospital_pharmacy
from . import hospital_insurance
from . import ambulance
from . import ambulance_request
from . import donor
from . import blood_bag
from . import transfusion
from . import hospital_dashboard
from . import room_dashboard
from . import department_dashboard
from . import pharmacy_dashboard
from . import blood_bank_dashboard
from . import prescription
from . import patient_history_wizard
from . import lab_test_type
from . import lab_request
from . import lab_result
